version: '3.9'
services:

  wallet_db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: 'wallet'
      POSTGRES_DB: 'wallet'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_PORT: 5432

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret_cookie}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  user:
    build:
      context: ../user-management
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  wallet:
    build:
      context: ../wallet
      dockerfile: Dockerfile
    depends_on:
      - wallet_db
      - rabbitmq
    environment:
      PORT: 8081
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: wallet
      DB_PASSWORD: password
      DB_MIN_POOLSIZE: 1
      DB_MAX_POOLSIZE: 30
      NODE_ENV: production
      DB_NAME: wallet

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wallet
