export enum ExceptionCode {
  INVALID_MONEY = 'WALLET__INVALID_MONEY',
  INCOMPATIABLE_CURRENCY = 'WALLET__INCOMPATIABLE_CURRENCY',
  PERSISTENCE = 'WALLET__PERSISTENCE',
  NOT_FOUND = 'WALLET__NOT_FOUND',
}
