export enum TransactionCode {
  INSUFFICIENT_FUND = 'TRANSACTION__INSUFFICIENT_FUND',
  PERSISTENCE = 'TRANSACTION__PERSISTENCE',
  NOT_FOUND = 'TRANSACTION__NOT_FOUND',
  INVALID_TRANSACTION_MONEY = 'TRANSACTION__INVALID_TRANSACTION_MONEY',
}
