export enum WalletCode {
  INVALID_MONEY = 'WALLET__INVALID_MONEY',
  INCOMPATIABLE_CURRENCY = 'WALLET__INCOMPATIABLE_CURRENCY',
  PERSISTENCE = 'WALLET__PERSISTENCE',
  NOT_FOUND = 'WALLET__NOT_FOUND',
  INVALID_TRANSACTIONS = 'WALLET__INVALID_TRANSACTIONS',
  WALLET__INCOMPATIABLE_CURRENCY = 'WALLET__INCOMPATIABLE_CURRENCY',
}
